FROM mhart/alpine-node:9.11.1 as app-builder

ADD yarn.lock /yarn.lock
ADD package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
ENV REACT_APP_MOCK=https://5adef892bf932f0014d11b48.mockapi.io/api


WORKDIR /app
COPY . /app

RUN yarn --ignore-engines

RUN yarn run build-css
RUN yarn run build

FROM nginx:stable-alpine

RUN rm -rf /etc/nginx/conf.d
COPY deploy/conf /etc/nginx

COPY --from=app-builder /app/build /usr/share/nginx/html

EXPOSE 80