version: '3.5'
services:
  client:
    image: registry.chas.school/mercury-client:latest
    networks:
      - traefik
    deploy:
      labels:
        traefik.port: '80'
        traefik.backend: 'mercury_client'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:mercury.chas.school'
    env_file:
      - ../.env

networks:
  traefik:
    external: true
